"""
{{DISPLAY_NAME}} - FastAPI Application
Generated by OneClickOps
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List
import os
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="{{DISPLAY_NAME}}",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class HealthResponse(BaseModel):
    status: str
    service: str
    version: str

class ItemBase(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    is_active: bool = True

class Item(ItemBase):
    id: int

items_db: List[Item] = []
item_counter = 0

@app.get("/", response_model=HealthResponse)
async def root():
    return HealthResponse(status="healthy", service="{{PROJECT_NAME}}", version="1.0.0")

@app.get("/health", response_model=HealthResponse)
async def health_check():
    return HealthResponse(status="healthy", service="{{PROJECT_NAME}}", version="1.0.0")

@app.get("/ready")
async def readiness_check():
    return {"status": "ready"}

@app.get("/items", response_model=List[Item])
async def list_items():
    return items_db

@app.post("/items", response_model=Item, status_code=201)
async def create_item(item: ItemBase):
    global item_counter
    item_counter += 1
    new_item = Item(id=item_counter, **item.dict())
    items_db.append(new_item)
    return new_item

@app.get("/items/{item_id}", response_model=Item)
async def get_item(item_id: int):
    for item in items_db:
        if item.id == item_id:
            return item
    raise HTTPException(status_code=404, detail="Item not found")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", "{{SERVICE_PORT}}")))
